### PR TITLE
Moved transferring markers from writer to batch

### LINKED ISSUE #862: Move transferring markers from from writer to batch
We decided that model `writer` will be a place where `DocumentFragment#markers` will be transferred to `Document#markers`. Unfortunately, this can be done here because:
1. it simply doesn't work
2. won't work for well for undo

I'll try to add markers as `MakerOperation` in `batch.insert`.

### PR DESCRIPTION
**Pull request by oskarwrobel**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Moved transferring markers from writer to batch. Closes #862.

---

### CODE REVIEW

File: src/model/delta/insertdelta.js [hunk 1]
```diff
@@ -95,7 +104,44 @@ register( 'insert', function( position, nodes ) {
 	delta.addOperation( insert );
 	this.document.applyOperation( insert );
 
+	// When element is a DocumentFragment we need to move its markers to Document#markers.
+	if ( nodes instanceof DocumentFragment ) {
+		for ( const marker of nodes.markers ) {
```
Comment (pjasiun) [inline src/model/delta/insertdelta.js]: I this case destructuring might be fine (and nice) `for ( const [ markerName, markerRange ] of nodes.markers )`.

File: src/model/delta/insertdelta.js [hunk 2]
```diff
@@ -95,7 +104,44 @@ register( 'insert', function( position, nodes ) {
...
 } );
 
 DeltaFactory.register( InsertDelta );
+
+// Moves range relative to given position.
+//
+// @param {module:engine/model/range~Range} range
+// @param {module:engine/model/position~Position} position
+// @returns {module:engine/model/range~Range} Moved range.
+function moveRange( range, position ) {
```
Comment (pjasiun) [inline src/model/delta/insertdelta.js]: This function name is a little miss leading. You know, it sounds like you move range, but the range is the same. Maybe something like `migrateRanges` would be better.

File: src/model/delta/insertdelta.js [hunk 3]
```diff
@@ -95,7 +104,44 @@ register( 'insert', function( position, nodes ) {
...
+	let startPath = range.start.path.concat( [] );
+	let endPath = range.end.path.concat( [] );
+
+	// Move range out of DocumentFragment.
+	startPath.shift();
+	endPath.shift();
+
+	// Set Range on position.
+	startPath = position.path.concat( startPath );
+	endPath = position.path.concat( endPath );
```
Comment (pjasiun) [inline src/model/delta/insertdelta.js]: Isn't it done automatically by the position constructor?

Comment (pjasiun) [inline src/model/delta/insertdelta.js]: https://github.com/ckeditor/ckeditor5-engine/blob/a7409be9830c7fa1fb9c921ee6b7eaaa0289e7c4/src/model/position.js#L66

**Comment by pjasiun** [comment]
The change is fine for me. I commented some details.

File: src/model/delta/insertdelta.js [hunk 4]
```diff
@@ -95,7 +104,44 @@ register( 'insert', function( position, nodes ) {
...
+	if ( nodes instanceof DocumentFragment ) {
+		for ( const marker of nodes.markers ) {
+			const doc = this.document;
+			const range = moveRange( marker[ 1 ], position );
+			const markerDelta = new MarkerDelta();
+			const markerOperation = new MarkerOperation( marker[ 0 ], null, range, doc.markers, doc.version );
+
+			this.addDelta( markerDelta );
+			markerDelta.addOperation( markerOperation );
+			doc.applyOperation( markerOperation );
```
Comment (pjasiun) [inline src/model/delta/insertdelta.js]: You can call `this. setMarker` instead of doing it manually. It should be safer.

Comment (scofalik) [inline src/model/delta/insertdelta.js]: Well, the funny thing about all of these is that the markers might be just temporary markers and you might not want to add them do the document, undo, etc.

Comment (scofalik) [inline src/model/delta/insertdelta.js]: In fact, since we cannot (at the moment) use `Batch` API on `DocumentFragment` these markers are for sure not added to the document, so I hesitate whether we should add them to the document at all.

Comment (scofalik) [inline src/model/delta/insertdelta.js]: On the other hand if you add markers with data that is added through `Batch` API it might be assumed that you want those markers synchronized (added to document, undo, etc.) too. I am fine with this.

Comment (scofalik) [inline src/model/delta/insertdelta.js]: > You can call `this.setMarker` instead of doing it manually. It should be safer.

This is a good point I wanted to point the same (before I got the doubts I described above :P)

File: src/model/delta/insertdelta.js (hunk 2 above)
Comment (scofalik) [inline src/model/delta/insertdelta.js]: +1

Comment (scofalik) [inline src/model/delta/insertdelta.js]: I also wonder whether one of many transformations methods in `Range` and `Position` may get handy, for example `Position#_getCombined`.

File: src/model/delta/insertdelta.js (hunk 3 above)
Comment (oskarwrobel) [inline src/model/delta/insertdelta.js]: I expect the same but:
- position where I want to insert element is `<root>abc[]</root>` -> path is `[ 3 ]`
- start position of my range in doc frag `<docfrag><p>d[]ef<p></docfrag>` `[ 0, 1 ]`

When I create position in this way `new Position( root, marker.start.path )` the result path will be `[ 0, 1 ]` but I need `[ 3, 0, 1 ]`.

File: src/model/delta/insertdelta.js (hunk 2 above)
Comment (scofalik) [inline src/model/delta/insertdelta.js]: If you use `_getTransformedByMove`, `sourcePosition` should be the first position in document fragment ( `Position.createAt( range.root )` ), `targetPosition` should be equal to passed `position` and `howMany` should be number of document fragment children.

Or you can go with `_getCombined`:
```javascript
return new Range(
	range.start._getCombined( Position.createAt( range.root ), position ),
	range.end._getCombined( Position.createAt( range.root ), position )
);
```

Try those and let me know if those worked.

File: src/model/delta/insertdelta.js (hunk 4 above)
Comment (pjasiun) [inline src/model/delta/insertdelta.js]: > On the other hand if you add markers with data that is added through Batch API it might be assumed that you want those markers synchronized (added to document, undo, etc.) too. I am fine with this.

Yea, I think that adding fragment with markers to the document is... adding markers to the document. One expects that they will be added. If I want to add only elements, I add elements and markers add to the `document.markers` directly, without `batch` API.

File: src/model/delta/insertdelta.js (hunk 3 above)
Comment (pjasiun) [inline src/model/delta/insertdelta.js]: Ach, I see. That's fine then.

File: src/model/delta/insertdelta.js (hunk 2 above)
Comment (oskarwrobel) [inline src/model/delta/insertdelta.js]: Looks like `Position#_getCombined` is exactly what I need 👌. Why is this method protected?

**Comment by pjasiun** [comment]
I forget to copy a commit message, but it was an internal change which should be introduced with the feature at the first place.

**Comment by oskarwrobel** [comment]
You can change message of last commit by `git commit --amend` and `git push origin master --force`

**Comment by oskarwrobel** [comment]
But pushing with `--force` to the master is risky :)

**Comment by pjasiun** [comment]
I know, but I don't think this message should go to the changelog. And I know @Reinmar will kill me for the wrong commit message, but I like living on the edge. :)

**Comment by Reinmar** [comment]
You can't amend merge commit AFAIR. Just commit an empty commit right after the merge, this time with the proper message. That will be fine.

**Comment by pjasiun** [comment]
You can, I just did it in `theme-lark`. But I agree that force push to the master is not a good idea in most cases.
