### PR TITLE
Prevent rendering when one is in the `change` block.

### LINKED ISSUE #1528: Nested contenteditables + comment markers make page jumps
**How to reproduce?**
1. Create an image
2. Write some text in its caption
3. Create a comment to the caption
4. Scroll down the page. 
5. Select text in the caption
6. Select text in the main content editable element

**Current behavior:**
Scroll jumps to the top.

**Additional info**
Reproducible on Chrome, Safari
The same happens with table cells.

I've tried to debug it with @oskarwrobel and here are our thoughts:

Clicking the marker makes the comment's contenteditable active and triggers its rendering. Then Clicking outside of it, makes it inactive, rerenders the comment and rerenders the main content editable element. It triggers two times https://github.com/ckeditor/ckeditor5-engine/blob/5c0a34d6f277fed063d8ed40af5b8ebda4690e14/src/view/renderer.js#L756
which probably doesn't find the selection in the editor for the second time, thus it creates a selection for a while at the top of the editor and scrolls to it. 

Possible solutions:
* Switch these two lines - https://github.com/ckeditor/ckeditor5-engine/blob/5c0a34d6f277fed063d8ed40af5b8ebda4690e14/src/view/renderer.js#L231-L232 by @oskarwrobel. Not sure if it doesn't break something else.
* Add `setTimeout 0` in comments when they change state between active and inactive.
* Add `domElement.focus( { preventScroll: false } )`. Unfortunately, it works only in Chrome, doesn't work in Safari and it looks like a "postfixer".

WDYT?
cc @pjasiun @Reinmar

### PR DESCRIPTION
**Pull request by pjasiun**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Internal: Prevent rendering when one is in the `change` block. Closes #1528.

### CODE REVIEW

File: src/controller/editingcontroller.js [hunk 1]
```diff
@@ -70,6 +70,19 @@ export default class EditingController {
 		const selection = doc.selection;
 		const markers = this.model.markers;
 
+		// Various plugins listen on model changes (on selection change, post fixers, etc.) and change the view as a
```
Comment (Reinmar) [inline src/controller/editingcontroller.js]: When plugins listen on model changes (on selection change, post fixers, etc) and change the view as a result of model's change, they might trigger view rendering before the conversion is completed (e.g. before the selection is converted). We disable rendering for the length of the outermost model change() block to prevent that.

See https://github.com/ckeditor/ckeditor5-engine/issues/1528

File: src/model/model.js [hunk 2]
```diff
@@ -487,6 +491,22 @@ export default class Model {
 	 * @param {module:engine/model/writer~Writer} writer `Writer` instance that has been used in the change block.
 	 */
 
+	/**
+	 * Fired when entering the first {@link module:engine/model/model~Model#enqueueChange} or
+	 * {@link module:engine/model/model~Model#change} block of the pending changes.
```
Comment (Reinmar) [inline src/model/model.js]: That "pending changes" thing is misleading. It sounds like this is the Nth+ block. A one that was scheduled but needed to be postponed so it's "pending". Isn't it just the "outermost enqueueChange/change block"?

File: src/model/model.js [hunk 3]
```diff
@@ -487,6 +491,22 @@ export default class Model {
...
+	 *
+	 * @protected
+	 * @event _beforeChanges
+	 */
+
+	/**
+	 * Fired when leaving the last {@link module:engine/model/model~Model#enqueueChange} or
+	 * {@link module:engine/model/model~Model#change} block of the pending changes.
```
Comment (Reinmar) [inline src/model/model.js]: The same as above.

File: src/view/view.js [hunk 4]
```diff
@@ -126,6 +126,14 @@ export default class View {
 		 */
 		this._postFixersInProgress = false;
 
+		/**
+		 * Internal flag to temporary disable rendering. See usage in the editing controller.
+		 *
+		 * @protected
+		 * @member {Boolean} module:engine/view/view~View#_disabledRendering
+		 */
+		this._disabledRendering = false;
```
Comment (Reinmar) [inline src/view/view.js]: `_renderingDisabled` would be more grammatical. Plus, you have `_renderingInProgress` above already.

File: tests/controller/editingcontroller.js [hunk 5]
```diff
@@ -339,6 +339,112 @@ describe( 'EditingController', () => {
 			expect( getViewData( editing.view, { withoutSelection: true } ) )
 				.to.equal( '<p></p><p>f<span>oo</span></p><p>bar</p>' );
 		} );
+
+		describe( 'rendering preventing in the change block', () => {
```
[the remark this answers is not in the document]
Comment (Reinmar) [reply tests/controller/editingcontroller.js]: or even:

preventing rendering while in the change() block

File: tests/controller/editingcontroller.js [hunk 6]
```diff
@@ -339,6 +339,112 @@ describe( 'EditingController', () => {
...
+			let renderSpy;
+
+			beforeEach( () => {
+				renderSpy = sinon.spy();
+
+				editing.view.on( 'render', renderSpy );
+			} );
+
+			it( 'should not call render in the change block', () => {
```
Comment (Reinmar) [inline tests/controller/editingcontroller.js]: model.change()

File: tests/controller/editingcontroller.js [hunk 7]
```diff
@@ -339,6 +339,112 @@ describe( 'EditingController', () => {
...
+				model.change( writer => {
+					executeSomeModelChange( writer );
+
+					expect( renderSpy.called ).to.be.false;
+				} );
+
+				expect( renderSpy.called ).to.be.true;
+			} );
+
+			it( 'should not call render in the change block even if view change was called', () => {
```
Comment (Reinmar) [inline tests/controller/editingcontroller.js]: view.change()

**Comment by Reinmar** [comment]
Except for some wording and naming, this LGTM.

**Comment by Reinmar** [comment]
Tests look good so I'm merging it.
