### PR TITLE
T/1172-b Conversion refactor

### LINKED ISSUE #1172: Conversion refactor
I am opening this ticket to have a place for discussion about upcoming conversion refactor.

## Goals

There are a few goals that we want to achieve with this.

The first goal is to stop converting an incorrect model state to the view. This happens now because we fire model-to-view conversion after each atomic change on the model.

There is also a problem with mapping during conversion. Sometimes we need to map non-existing model position/range to the view (a case for remove). Sometimes we want to map an element from the model to the view, but the element was already mapped to another element (a case for rename and move AFAIR). It would be perfect if those problems would vanish away.

The second goal is to make it easier to write converters. At the moment, converters are the most complicated part of developing a feature. For a new developer, it may be not clear what exactly they have to do to write a correct converter.

This is also connected with providing more / different / better / easier to use conversion helpers. Now we have more knowledge about how the converters actually look, so we know what kind of helpers we can introduce.

Additionally, markers conversion isn't pretty right now. It'd be nice to revisit it.

The bonus goal is to prepare an environment where we can easily hook callbacks / fixers that should react to changes in the model.

Keep in mind, that developers have their own experiences and are accustomed to some patterns. If the solution is easier for the user, it is probably better.

Think if there is anything that can be improved in view-to-model conversion. Since this topic all began from talking about "converting model changes to view on `changesDone`" it was natural, that we mostly focused on model-to-view conversion. In my opinion, view-to-model conversion is fine, but I might be missing something.

## Related tickets

https://github.com/ckeditor/ckeditor5-engine/issues/829 - Simplify model to view conversion
https://github.com/ckeditor/ckeditor5-engine/issues/736 - Add more conversion helpers
https://github.com/ckeditor/ckeditor5-engine/issues/778 - Change-based conversion can be really confusing
https://github.com/ckeditor/ckeditor5-engine/issues/779 - It shouldn't be needed to listen on 3 events to convert an attribute
https://github.com/ckeditor/ckeditor5-engine/issues/945 - Consider simplifying attribute conversion

### Thinking out of the box

I'd like to make it clear, that we should try to forget about how conversion looks now. Of course, we have experience, we know what worked and what did not work. However, maybe we could come up with a totally different idea for conversion mechanism.

The only assumptions to make are:
1. There is a model element which is composed of name and attributes. We need to convert that model element to a view element. 
2. The model element might change. We need to reflect that change in the view.
3. The model might be in incorrect state after some changes are applied. We need a good solution how to fix the model if that happens.

### Limit amount of change types

This already has been tweaked a bit earlier. Anyway, This is a minimal set of changes that we need to support:
 - insert node,
 - remove node,
 - attribute changes.

Insert and remove changes handle, of course, removing and inserting elements, but also moving or renaming them.

Attribute changes are a bit more complicated. I am not sure what we need here. Unfortunately "add attribute" + "remove attribute" does not seem to be the correct way to change an attribute. Mostly because some elements require some attributes so removing attribute is forbidden. Take `listItem` for example. Changing it's `type` attribute should be converted "in one step", especially because it doesn't make sense to have a `listItem` without `type` attribute.

Maybe the solution is to have just one "attribute change" change type, and the converter should handle it all: inserting, removing and changing the attribute. The question is what we gain here - other than having to attach only one callback (instead of three, like now).

Another idea is to remove the element which attributes got changed and then insert it with the changed attribute. I am not sure how this will impact view tree and then DOM rendering. I am not sure how inefficient such solution would be. Thankfully, the biggest efficiency bottleneck is typing and attribute conversion is not connected with it.

### Conversion on `changesDone`

This is the original idea from which it all started. It is simple - do not convert model changes right away. Instead, buffer them. When all changes are applied, all callbacks and fixers did their changes, convert the model to the view. This should happen on `changesDone` event. At this moment, all fixers should already have fixed the model.

What do we gain from this solution? Mostly, the converters will be easier to write because they won't need to convert incorrect model states.

How to enable conversion on `changesDone`? There are a couple of ideas here:

1. Mark changed elements. Have a data structure that will keep changes done to the model: which elements were removed, which were added and which attributes changed. This is a bit difficult for `Text` instances. Text changes might need to be kept as `LivePosition`s, especially when whole text node was removed. On `changesDone` iterate through this data structure and apply changes to the view one by one. This is the simplest and original proposal. I'd treat this as a "fallback solution". It does not change a lot in the conversion itself, it just postpones the whole conversion to a later stage. It solves some of our problems. If we won't come up with something better, this should be okay.
2. Copy model or parts of the model to diff them later. Instead of tracking down each change, we could copy the whole model when first change is applied and then diff old (saved) model with the new one. Unfortunately, I fear that this would be too inefficient for typing.
3. Save which model elements have changed. Then convert them to the view and diff them with the actual view. This idea is similar to what we have right now in view->DOM rendering. We only change what really changed. I am not sure, but AFAICS this solution could also resolve some problems with mapping.

Do not forget about markers! Markers are also a part of the model and need to be converted on `changesDone`. We would have to store which markers have changed, and how. The exact implementation will probably depend on the chosen solution for model tree conversion.

Those ideas do not touch `change` callbacks, though. Those callbacks / fixers, similarly to converters, are now a bit too complicated. At the end of this post I've included a list of all callbacks listening to `change` event.

### Decouple building and inserting elements

We came from an idea that we are converting changes, not model state. This is why we'd rather say "convert image insertion" rather than "convert image element". On the other hand, it is much easier to think that "`listItem` model element should be represented as `<li></li>` in view". People are familiar with this kind of thinking. We should take it into consideration.

Hence, I propose to think about decouple inserting elements and building elements. Inserting is same anyway for most features. For now, only lists have their own needs for inserting -- when you insert an element between `listItem`s, in view you need to break `<ul>`/`<ol>` element. Similarly, when you remove an element, it may happen that two lists need to be merged.

The reason for this proposal is that maybe if we think about "building" elements, it will be easier to refactor conversion mechanisms and propose new conversion utilities.

This idea is strongly connected with rebuilding items a lot of time (for example, rebuild the whole item when its attribute changed). We need to think how elements change and what impact does rebuilding have on creating a view structure and then DOM.

### Firing event before the change is applied to the model

This is a wild idea and I don't know what it would achieve expect of giving us more possibilities but I just wanted to throw it here and see if maybe you will find it useful.

The idea is simple: instead of applying a change to the model right away, fire an event. Listeners would be able to modify or cancel the change.

### Do we need consumables?

This was brought up during talks and is not originally my idea. The question was whether we need consumables and how do we use them at the moment. The doubt was that consumables have the same role as event canceling. The bottom line was that we maybe need them in view-to-model conversion but probably are able to remove them from model-to-view conversion.

Of course, if we will go with "building" items, the model-to-view conversion will get a bit similar to the view-to-model conversion. Then we might need consumables to build elements from the model in a right way.

### Use cases for `change` event other than `ModelConversionDispatcher`

CKE5 uses `change` event for following callbacks / fixing:

 - autoformatting (typing of certain characters are detected on `change` event),
 - image caption (adding `image` element is detected and if the `image` does not have `caption` element, the element is added),
 - lists fixer (a lot of incorrect scenarios related with `type` and `indent` attributes are detected and fixed),
 - auto paragraphing (when an empty root is detected, `paragraph` element is inserted),
 - change buffer is updated after each `change` event (typing),
 - undo (undo stack is refreshed after each change on the model),
 - image upload.

Additionally, these are Letters use cases:

 - document structure is fixed to always have title and body,
 - comments management heavily depends on detecting marker changes,
 - saving changes to send to other clients,
 - comments position in the sidebar is refreshed after each change.

I think that in overall, there are two types of callbacks:
 - ones that care about model state or how it was changed and then fix the model or refresh some other states,
 - others that have to react to every change, mostly to track it.

### What helpers do we need?

This is to bootstrap a work that has to be done with conversion helpers. There was an idea to drop converter builders and instead provide a set of utility functions that will be simpler to use but will produce more focused converters.

We need to study how do we use converter builders. Which cases need to be ported to utility functions. Then, we need to see what was impossible to do using builders.

A short list of helpers that we need. Was not researched much yet:
 - model element <-> view element (by element name),
 - model attribute <-> view element (by names),
 - model attribute <-> view attribute (by names),
 - markers conversion,
 - collapsed selection conversion (it breaks attributes and inserts empty attribute elements),
 - **new** view style converter (make it easy to add and remove a part of style attribute),
 - **new** view class converter (make it easy to add and remove a part of class attribute),
 - **new** wrapper converters (case where generated view structure is wrapped in an element, for example `<figure>` element in image feature)

## Tasks

A list of tasks that we need to do no matter how we proceed with this refactoring.

1. Clean `view.writer`. For example, it has `rename` method and I am not sure if it is used at all.
2. Check how `UIElement`s are created and added to the view tree. Try to come up with an API to manage `UIElement`s better.

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other: Conversion refactoring. Introduced `model.Differ`. Changes now will be converted after all changes in a change block are done. Closes #1172.

### CODE REVIEW

File: src/conversion/mapper.js [hunk 1]
```diff
@@ -368,7 +379,7 @@ export default class Mapper {
 	 *		We are in the text node so we can simple find the offset.
 	 *		<p>fo<b>ba|r</b>bom</p> -> expected offset: 2, actual offset: 2 -> position found
 	 *
-	 * @private
+	 * @protected
```
Comment (pjasiun) [inline src/conversion/mapper.js]: It should be still private.

File: src/conversion/mapper.js [hunk 2]
```diff
@@ -202,12 +222,15 @@ export default class Mapper {
 	 *
 	 * @fires modelToViewPosition
 	 * @param {module:engine/model/position~Position} modelPosition Model position.
+	 * @param {Boolean} [isPhantom=false] Should be set to `true` if the model position to map is pointing to a place
+	 * in model tree which no longer exists. For example, it could be an end of a removed model range.
 	 * @returns {module:engine/view/position~Position} Corresponding view position.
 	 */
-	toViewPosition( modelPosition ) {
+	toViewPosition( modelPosition, isPhantom = false ) {
```
Comment (pjasiun) [inline src/conversion/mapper.js]: Instead of `isPhantom` -> `options.isPhantom`.

File: src/conversion/model-to-view-converters.js [hunk 3]
```diff
@@ -91,6 +90,34 @@ export function insertText() {
...
+ *
+ * @returns {Function} Remove event converter.
+ */
+export function remove() {
+	return ( evt, data, conversionApi ) => {
+		// Find view range start position by mapping model position at which the remove happened.
+		const viewStart = conversionApi.mapper.toViewPosition( data.position );
+
+		const modelEnd = data.position.getShiftedBy( data.length );
+		const viewEnd = conversionApi.mapper.toViewPosition( modelEnd, true );
```
Comment (pjasiun) [inline src/conversion/model-to-view-converters.js]: `const viewEnd = conversionApi.mapper.toViewPosition( modelEnd, { isPhantom: true } );` would be more readable.

File: src/conversion/model-to-view-converters.js [hunk 4]
```diff
@@ -108,107 +135,95 @@ export function insertUIElement( elementCreator ) {
...
-		// Marker that is collapsed has consumable build differently that non-collapsed one.
-		// For more information see `addMarker` and `removeMarker` events description.
-		// If marker's range is collapsed - check if it can be consumed.
-		if ( markerRange.isCollapsed && !consumable.consume( markerRange, eventName ) ) {
-			return;
-		}
-
-		// If marker's range is not collapsed - consume all items inside.
-		for ( const value of markerRange ) {
-			if ( !consumable.consume( value.item, eventName ) ) {
```
Comment (pjasiun) [inline src/conversion/model-to-view-converters.js]: Why consume is removed?

File: src/conversion/modelconversiondispatcher.js [hunk 5]
```diff
@@ -131,64 +146,49 @@ export default class ModelConversionDispatcher {
...
+				continue;
+			}
 
-		if ( type == 'rename' && data.element.root.rootName == '$graveyard' ) {
-			return;
+			if ( entry.type == 'insert' ) {
+				this.convertInsert( Range.createFromPositionAndShift( entry.position, entry.length ) );
+			} else if ( entry.type == 'remove' ) {
+				this.convertRemove( entry.position, entry.length, entry.name );
+			} else {
```
Comment (pjasiun) [inline src/conversion/modelconversiondispatcher.js]: Comment.

File: src/model/differ.js [hunk 6]
```diff
@@ -0,0 +1,774 @@
...
+	 * @returns {Array.<Object>} Diff between old and new model tree state.
+	 */
+	getChanges() {
+		// Will contain returned results.
+		const diffSet = [];
+
+		// Check all changed elements.
+		for ( const element of this._changesInElement.keys() ) {
+			// If the element is inside other changed element, skip changes in this element.
+			if ( this._isInsertedOrRemoved( element ) ) {
```
Comment (pjasiun) [inline src/model/differ.js]: Add comment that it's all about children.

File: src/model/differ.js [hunk 7]
```diff
@@ -0,0 +1,774 @@
...
+				continue;
+			}
+
+			// Get changes for this element and sort them.
+			const changes = this._changesInElement.get( element ).sort( ( a, b ) => {
+				if ( a.offset === b.offset ) {
+					if ( a.type != b.type ) {
+						return a.type == 'remove' ? -1 : 1;
```
Comment (pjasiun) [inline src/model/differ.js]: Comment needed.

File: src/model/differ.js [hunk 8]
```diff
@@ -0,0 +1,774 @@
...
+// - 'a' for 'attribute' - when item at that position has it attributes changed.
+function _generateActionsFromChanges( oldChildrenLength, changes ) {
+	const actions = [];
+
+	let offset = 0;
+	let oldChildrenHandled = 0;
+
+	for ( const change of changes ) {
+		if ( change.offset > offset ) {
+			actions.push( ...'e'.repeat( change.offset - offset ).split( '' ) );
```
Comment (pjasiun) [inline src/model/differ.js]: Comment "fill holes between end of one change and beginning of another with 'e'".

File: src/model/differ.js [hunk 9]
```diff
@@ -0,0 +1,774 @@
...
+	return snapshot;
+}
+
+// Generates array of actions for given changes set.
+// It simulates what `diff` function does.
+// Generated actions are:
+// - 'e' for 'equal' - when item at that position did not change,
+// - 'i' for 'insert' - when item at that position was inserted,
+// - 'r' for 'remove' - when item at that position was removed,
+// - 'a' for 'attribute' - when item at that position has it attributes changed.
```
Comment (pjasiun) [inline src/model/differ.js]: A single sample would be great.

File: src/model/differ.js [hunk 10]
```diff
@@ -0,0 +1,774 @@
...
+		for ( const [ key, oldValue ] of oldAttributes ) {
+			// Check what is the new value of the attribute (or if it was removed).
+			const newValue = newAttributes.has( key ) ? newAttributes.get( key ) : null;
+
+			// If values are different (or attribute was removed)...
+			if ( newValue !== oldValue ) {
+				// Add diff item.
+				diffs.push( {
+					type: 'attribute',
+					position: range.start,
```
Comment (pjasiun) [inline src/model/differ.js]: It's strange that I get both position and range.

File: src/model/differ.js [hunk 11]
```diff
@@ -0,0 +1,774 @@
...
+			if ( old.type == 'attribute' ) {
+				if ( inc.offset <= old.offset ) {
+					old.offset += inc.howMany;
+				} else if ( inc.offset < oldEnd ) {
+					const howMany = old.howMany;
+
+					old.howMany = inc.offset - old.offset;
+
+					// Unshift to prevent further processing of this change.
+					changes.unshift( { type: 'attribute', offset: incEnd, howMany: howMany - old.howMany, count: this._changeCount++ } );
```
Comment (pjasiun) [inline src/model/differ.js]: Comment why you add change in the first place is needed.

Comment (pjasiun) [reply src/model/differ.js]: And since you unshift because you know that this function is called in the loop, the loop should be moved inside the function.

File: src/model/differ.js [hunk 12]
```diff
@@ -0,0 +1,774 @@
...
+				} else if ( inc.offset < oldEnd ) {
+					if ( incEnd <= oldEnd ) {
+						const howMany = old.howMany;
+
+						old.howMany = inc.offset - old.offset;
+
+						const howManyAfter = howMany - old.howMany - inc.howMany;
+
+						// Unshift to prevent further processing of this change.
+						changes.unshift( { type: 'attribute', offset: inc.offset, howMany: howManyAfter, count: this._changeCount++ } );
```
Comment (pjasiun) [inline src/model/differ.js]: Why?

File: src/model/differ.js [hunk 13]
```diff
@@ -0,0 +1,774 @@
...
+		}
+
+		if ( inc.type == 'attribute' ) {
+			if ( old.type == 'insert' ) {
+				if ( inc.offset < old.offset && incEnd > old.offset ) {
+					if ( incEnd > oldEnd ) {
+						const changeItem = { type: 'attribute', offset: oldEnd, howMany: incEnd - oldEnd, count: this._changeCount++ };
+
+						for ( const oldChange of changes ) {
+							this._handleChange( changeItem, oldChange, changes );
```
Comment (pjasiun) [inline src/model/differ.js]: Why?

File: src/model/differ.js [hunk 14]
```diff
@@ -0,0 +1,774 @@
...
+			if ( change.newRange != null ) {
+				result.push( { name, range: change.newRange } );
+			}
+		}
+
+		return result;
+	}
+
+	/**
+	 * Calculates diff between old model tree state (before all the buffered operations) and the new model tree state
```
Comment (pjasiun) [inline src/model/differ.js]: `(before all the buffered operations)` -> `(since the last {@link #reset})`?

File: src/conversion/model-to-view-converters.js (hunk 4 above)
Comment (scofalik) [reply src/conversion/model-to-view-converters.js]: For some time there were no consumables and I forgot to bring back this part of code.

File: src/model/differ.js (hunk 10 above)
Comment (scofalik) [reply src/model/differ.js]: `position` is useful for further sorting (as other changes has `position` too), but I will remove it from the final results. BTW. attribute change item also has `length` which is not used at all - I will remove it.

File: src/conversion/mapper.js [hunk 15]
```diff
@@ -460,19 +471,32 @@ export default class Mapper {
...
-	 *		const viewElement = data.mapper.toViewElement( modelElement );
-	 *		// ... Do something with `viewElement` and set `data.viewPosition`.
+	 * 		// Assume that there is "customElement" model element and whenever position is before it, we want to move it
+	 * 		// to the inside of the view element bound to "customElement".
+	 *		mapper.on( 'modelToViewPosition', ( evt, data ) => {
+	 *			if ( data.isPhantom ) {
+	 *				return;
+	 *			}
+	 *
+	 *			const sibling = modelPosition.nodeBefore; // Might crash for phantom position that does not exist in model.
```
Comment (pjasiun) [inline src/conversion/mapper.js]: `modelPosition.nodeBefore` -> `data.modelPosition.nodeBefore`?

File: src/conversion/model-to-view-converters.js [hunk 16]
```diff
@@ -496,65 +412,98 @@ export function highlightElement( highlightDescriptor ) {
...
-			viewElement.getCustomProperty( highlightHandlingMethod )( viewElement, addMarker ? descriptor : descriptor.id );
+			viewElement.getCustomProperty( 'addHighlight' )( viewElement, descriptor );
 		}
 	};
 }
 
 /**
- * Function factory, creates a default model-to-view converter for removing {@link module:engine/view/uielement~UIElement ui element}
- * basing on marker remove change.
+ * Function factory, creates a converter that converts model marker add/change/remove to the view.
```
Comment (pjasiun) [inline src/conversion/model-to-view-converters.js]: Add, change?

File: src/conversion/modelconversiondispatcher.js [hunk 17]
```diff
@@ -68,11 +83,11 @@ import extend from '@ckeditor/ckeditor5-utils/src/lib/lodash/extend';
  *			// Add the newly created view element to the view.
  *			viewWriter.insert( viewPosition, viewElement );
  *
- *			// Remember to stop the event propagation if the data.item was consumed.
+ *			// Remember to stop the event propagation.
  *			evt.stop();
  *		} );
  *
- * Callback that "overrides" other callback:
+ * Callback that overrides other callback:
```
Comment (pjasiun) [inline src/conversion/modelconversiondispatcher.js]: I would remove this sample, it is too complicated, after reading it I understand less than before. Instead you could add a regular convresion for attribute->wrap (like bold).

File: src/model/differ.js (hunk 10 above)
Comment (scofalik) [reply src/model/differ.js]: It appears that I was wrong, both `length` and `position` are used in further processing but also both are not really needed later so they can be removed before changes are returned by `getChanges()`
