### PR TITLE
T/1619: Expose protectely insertElement and createUIElement conversion helpers

### LINKED ISSUE #1619: Tests on engine are failing
After merging https://github.com/ckeditor/ckeditor5-engine/pull/1606 and https://github.com/ckeditor/ckeditor5-engine/pull/1613 tests on engine are failing.

### PR DESCRIPTION
**Pull request by jodator**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Internal: Expose `insertElement()` and `createUIElement()` conversion helpers as protected functions. Closes #1619.

---

### Additional information

* This change is needed due to "catch-all" converters used in `getData()` from `dev-utils/model.js` used in tests
* as those method are internal I've left integration tests for them as now - I plan to do the same for `wrap()` method removal from public API. It will need to stay as export but will be tested only by integration tests (#1616). The `wrap()` method is used by attribute change "catch-all" converter in `dev-utils#getData()`

### CODE REVIEW

File: src/conversion/downcasthelpers.js [hunk 1]
```diff
@@ -532,19 +535,21 @@ function insertElement( elementCreator ) {
...
+ * Function factory that creates a converter which converts marker adding change to the
+ * {@link module:engine/view/uielement~UIElement view UI element}.
+ *
+ * The view UI element that will be added to the view depends on the passed parameter. See {@link ~insertElement}.
+ * In case of a non-collapsed range, the UI element will not wrap nodes but separate elements will be placed at the beginning
+ * and at the end of the range.
+ *
+ * This converter binds created UI elements with the marker name using {@link module:engine/conversion/mapper~Mapper#bindElementToMarker}.
+ *
+ * @param {module:engine/view/uielement~UIElement|Function} elementCreator A view UI element or a function returning the view element
```
Comment (pjasiun) [inline src/conversion/downcasthelpers.js]: `@protected`?
