### PR TITLE
Merge x merge becomes NoOperation if it is not going to be affected by undoing operation

### LINKED ISSUE #1543: New OT: Merge x merge special case not incorrect for redo
In `MergeOperation` x `MergeOperation` transformation, the merge may become a "do-nothing-merge" if both merge are same. That "do-nothing-merge" is a `MergeOperation` that moves `0` nodes from a node in graveyard (it merges a node that is already in graveyard). This has no impact on model tree but by not changing to `NoOperation` it is possible to "revert" this operation if the other `MergeOperation` got later undone.

Anyway, an example of such do-nothing-merge is: `MergeOperation $graveyard [ 0 ] -> main [ 1, 2 ] (howMany = 0)`. However, when this gets reversed, it becomes a `SplitOperation` with `howMany = 0` which is incorrect.

The scenario when the bug happens is this:

1. Client A and Client B merge at the same position.
2. Client A undoes and sends change to Client B.
3. Client B then undoes and generates "do-nothing-merge".
4. Client B redoes.
5. Editor throws.

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Internal: `MergeOperation` transformed by an equal `MergeOperation` becomes a `NoOperation` if it is not going to be affected by undoing operation. Closes #1543.

### CODE REVIEW

File: src/model/operation/transform.js [hunk 1]
```diff
@@ -1220,13 +1220,17 @@ setTransformation( MergeOperation, MergeOperation, ( a, b, context ) => {
...
-		a.sourcePosition = new Position( b.graveyardPosition.root, path );
-		a.howMany = 0;
+			a.sourcePosition = new Position( b.graveyardPosition.root, path );
+			a.howMany = 0;
 
-		return [ a ];
+			return [ a ];
+		} else {
+			return [ new NoOperation( 0 ) ];
+		}
```
Comment (pjasiun) [inline src/model/operation/transform.js]: A few words of comments are needed here. At least link to the ticket.
