### PR TITLE
T/919 ViewConverterBuilder#fromAttribute() sets wrong matcher

### LINKED ISSUE #919: ViewConverterBuilder#fromAttribute() sets wrong matcher
`ViewConverterBuilder#fromAttribute()`sets wrong matcher when attribute is not `style` or `class`. Correct objects for matchers are, for example, `{ class: 'abc' }` or `{ style: 'font-weight:bold;' }`, but: `{ attribute: { foo: 'bar', abc: 'xyz' } }`. `fromAttribute` would set `{ foo: 'bar' }`.

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: `ViewConverterBuilder#fromAttribute()` was creating incorrect matcher object for `Matcher` if passed attribute was other than `class` or `style`. Closes #919.

Minor upgrades to `ViewConversionBuilder`:
* converters from `ViewConversionBuilder` will not convert if "creator function" returned `null`.
* simplified view converters building by making `ViewConversionBuilder#toAttribute()` `value` param optional. If not set, the attribute value is taken from converted view element.

### CODE REVIEW

File: src/conversion/buildviewconverter.js [hunk 1]
```diff
@@ -314,13 +329,15 @@ class ViewConverterBuilder {
 	 * representing attribute key and attribute value or a function that returns an object with `key` and `value` properties.
 	 * If you provide creator function, it will be passed converted view element as first and only parameter.
 	 *
-	 *		buildViewConverter().for( dispatcher ).fromAttribute( 'style', { 'font-weight': 'bold' } ).toAttribute( 'bold', 'true' );
+	 *		buildViewConverter().for( dispatcher ).fromAttribute( 'alt' ).toAttribute( 'alt' );
+	 *		buildViewConverter().for( dispatcher ).fromAttribute( 'style', { 'font-weight': 'bold' } ).toAttribute( 'bold', true );
 	 *		buildViewConverter().for( dispatcher )
 	 *			.fromAttribute( 'class' )
-	 *			.toAttribute( ( viewElement ) => ( { key: 'class', value: viewElement.getAttribute( 'class' ) } ) );
+	 *			.toAttribute( ( viewElement ) => ( { key: 'class', value: 'class-' + viewElement.getAttribute( 'class' ) } ) );
```
Comment (Reinmar) [inline src/conversion/buildviewconverter.js]: What does this change mean?

File: src/view/matcher.js [hunk 2]
```diff
@@ -130,7 +130,7 @@ export default class Matcher {
 	 *			pattern: <pattern used to match found element>,
 	 *			match: {
 	 *				name: true,
- 	 *				attributes: [ 'title', 'href' ],
+	 *				attribute: [ 'title', 'href' ],
 	 *				classes: [ 'foo' ],
```
Comment (Reinmar) [inline src/view/matcher.js]: AFAICS, it should be `class` and `style` too.

File: src/conversion/buildviewconverter.js [hunk 3]
```diff
@@ -141,11 +141,21 @@ class ViewConverterBuilder {
...
+		if ( key === 'style' || key === 'class' ) {
+			pattern[ key ] = value;
+		} else {
+			pattern.attribute = {};
+			pattern.attribute[ key ] = value;
+		}
+
+		this.from( pattern );
+
+		this._from[ this._from.length - 1 ].attributeKey = key;
```
Comment (Reinmar) [inline src/conversion/buildviewconverter.js]: This is ugly. And where's this used anyway?

File: src/conversion/buildviewconverter.js [hunk 4]
```diff
@@ -141,11 +141,21 @@ class ViewConverterBuilder {
 	 * @param {String|RegExp} [value] View attribute value.
 	 * @returns {module:engine/conversion/buildviewconverter~ViewConverterBuilder}
 	 */
-	fromAttribute( key, value = /.*/ ) {
+	fromAttribute( key, value = /.+/ ) {
```
Comment (Reinmar) [inline src/conversion/buildviewconverter.js]: Why this change? There are empty attributes which values can be empty but still they "are".

File: src/conversion/buildviewconverter.js (hunk 3 above)
Comment (Reinmar) [inline src/conversion/buildviewconverter.js]: OK, I see where it's used (I must have made a typo looking for it before). Still, this is ugly, especially that you pass that key to `from()` anyway.

**Comment by Reinmar** [comment]
Regarding the commit message – I don't think that our commit parser can handle multiple types. A change may be of one type – usually, it will be the most significant one – so "feature" comes before "fix". But in this case, we have some minor changes which accompany the fix so you can list them as separate points under the fix. Like:

```
Fix: What was fixed. Closes #123.

* Changed x.
* Changed also y.
```

File: src/conversion/buildviewconverter.js (hunk 1 above)
Comment (scofalik) [inline src/conversion/buildviewconverter.js]: I've changed it to make the example relevant. If you want to map attribute to attribute without changing it, now you can do `.fromAttribute( 'class' ).toAttribute( 'class' )`.

File: src/view/matcher.js (hunk 2 above)
Comment (scofalik) [inline src/view/matcher.js]: My bad, I haven't looked at other keys, I had a problem with `attribute(s)` only (and it made me really angry, BTW.)

File: src/conversion/buildviewconverter.js (hunk 3 above)
Comment (scofalik) [inline src/conversion/buildviewconverter.js]: You pass it to `from()` but you can also use `from()` directly and pass whatever matcher/match object you want, so it is impossible to sniff whether `.fromAttribute( x ).toAttribute( y )` was used or not. I could check in `.toAttribute()` if `from` has just one value and it is `attribute` which has just one value, but I feel that that would be even uglier :P

File: src/conversion/buildviewconverter.js (hunk 4 above)
Comment (scofalik) [inline src/conversion/buildviewconverter.js]: Hmmm, I haven't thought of this. This is a good point. I agree that this change was wrong.

**Comment by scofalik** [comment]
I've pushed a couple of fixes and changed commit message.

File: src/conversion/buildviewconverter.js (hunk 3 above)
Comment (Reinmar) [inline src/conversion/buildviewconverter.js]: It's not about that. It's about not using `from()` if you actually need to do more than that (and apparently, `from()` is not a sufficient generalisation for this case). `from()` is 5 LOC, just repeat that code here and all will be fine.

File: src/conversion/buildviewconverter.js (hunk 1 above)
Comment (Reinmar) [inline src/conversion/buildviewconverter.js]: OK, I get it. I'll try to think about some better example.
