### PR TITLE
T/1055 Selection attributes should be cleared in an enqueueChanges block

### LINKED ISSUE #1055: Selection attributes are cleared from elements outside enqueue changes block
Original issue: https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-314216007

It appears that the fixer which clears selection attributes is applied outside of enqueue changes block, which messes up and crashes editor.

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fixed: Selection attributes should be cleared in an enqueueChanges block. Closes #1055.

---

### Additional information

When fixing this bug, I found a bug in `AttributeDelta` x `SplitDelta` transformation. It was similar to a bug that I fixed very recently - concerning `RenameDelta` x `SplitDelta` transformation. I also reformatted some code in `delta/transform/basic-transformation.js` to make it more clear.

As with other undo related bugs, tests will come in `ckeditor5-undo`.

### CODE REVIEW

**Comment by scofalik** [comment]
I've also added "undo mode" for `RemoveDelta` x `SplitDelta` transformation.

**Comment by scofalik** [comment]
https://github.com/ckeditor/ckeditor5-undo/pull/70

**Comment by scofalik** [comment]
Please do not review yet. I have to think about couple of things.

**Comment by Reinmar** [comment]
I labelled it with R- so to know that I don't need to look on it yet.

**Comment by scofalik** [comment]
Theoretically you can look at this. I just don't like what is happening to delta transformation special cases.

**Comment by pjasiun** [comment]
Please solve conflicts with the master branch.

**Comment by scofalik** [comment]
Done

File: src/model/documentselection.js [hunk 1]
```diff
@@ -707,9 +707,15 @@ function clearAttributesStoredInElement( changes, batch ) {
 		return;
 	}
 
-	const storedAttributes = Array.from( changeParent.getAttributeKeys() ).filter( key => key.startsWith( storePrefix ) );
+	const anyStoredAttributes = Array.from( changeParent.getAttributeKeys() ).some( key => key.startsWith( storePrefix ) );
```
Comment (Reinmar) [inline src/model/documentselection.js]: Why not having `storedAttributes`  and checking its length in the `if()` below?

Comment (scofalik) [inline src/model/documentselection.js]: Maybe I am not right, but...

we need to "refresh" `storedAttributes` array anyway in the `enqueueChanges` because something might have changed.

But, if that's true, we should not have `if( anyStoredAttributes )` because there might be no stored attributes ATM but, at least theoretically, may be some later?

Argh, this `enqueueChanges` is too damn difficult!

Comment (scofalik) [inline src/model/documentselection.js]: I think that we should make an agreement whether we are fine with `enqueueChanges` calls that do nothing. If we are fine with them, then we should not make conditional statements before `enqueueChanges`. The drawback is that we may fire more `changesDone` than needed, though.

If we are fine with empty `enqueueChanges` calls, we can remove that `if`.

Comment (Reinmar) [inline src/model/documentselection.js]: Damn... I haven't even thought about enqChanges not being synchronous ;<

Regarding empty enqChanges – I can't think of any issue that would cause, so I guess we can remove that `if()`.

**Comment by Reinmar** [comment]
I removed the `if()` which we discussed and unfortunately tests fail because they check how many times `enqChanges` was called (and it's now called all the time). So you need to update these tests somehow.

**Comment by scofalik** [comment]
Done. I've removed failing checks from the tests and added one dedicated test that checks whether the change is done in enqueue changes block.

**Comment by Reinmar** [comment]
And now this branch has conflicts :D

**Comment by scofalik** [comment]
I resolved conflicts. I also had to push some changes to tests in `enter`, `typing` and `list` repo because they started to crash. Those tests either incorrectly checked whether `enqueueChanges` block was used, or didn't use `enqueueChanges` block when they needed.
