### PR TITLE
Corrected RenameDelta x SplitDelta transformation special case

### LINKED ISSUE #1051: RenameDelta or RenameOperation transformation causes renaming incorrect nodes
Originally reported in comment: https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-313444518

What happens is that during undo rename is incorrectly applied to more than one element.

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fixed: Fixed a bug when renaming followed by merge or split, during undo, multiple elements where incorrectly renamed instead of one. Closes #1051.

### CODE REVIEW

File: src/model/delta/basic-transformations.js [hunk 1]
```diff
@@ -365,20 +366,25 @@ addTransformationCase( RenameDelta, SplitDelta, ( a, b, context ) => {
...
-	const splitPosition = new Position( a.position.root, a.position.path.slice( 0, -1 ) );
-
-	if ( a._cloneOperation instanceof InsertOperation ) {
-		// If element to split had it's name changed, we have to reflect this change in an element
-		// that is in SplitDelta's InsertOperation.
-		if ( b.operations[ 0 ].position.isEqual( splitPosition ) ) {
-			a._cloneOperation.nodes.getNode( 0 ).name = b.operations[ 0 ].newName;
-		}
+addTransformationCase( SplitDelta, RenameDelta, ( a, b, context ) => {
+	const undoMode = context.aWasUndone || context.bWasUndone;
```
Comment (Reinmar) [inline src/model/delta/basic-transformations.js]: Since in both cases we use `undoMode = a || b`, couldn't we store just `undoMode` in the context.

Comment (scofalik) [inline src/model/delta/basic-transformations.js]: That was my idea but I expect that there might be cases where we just want one or two.

**Comment by scofalik** [comment]
Additional integration tests are here: https://github.com/ckeditor/ckeditor5-undo/pull/68

File: src/model/delta/basic-transformations.js (hunk 1 above)
Comment (Reinmar) [inline src/model/delta/basic-transformations.js]: OK, that's what I thought. Makes sense.

File: src/model/delta/transform.js [hunk 2]
```diff
@@ -350,10 +354,21 @@ function padWithNoOps( deltas, howMany ) {
 // Using data given in `context` object, sets `context.insertBefore` and `context.forceNotSticky` flags.
 // Also updates `context.wasAffected`.
 function _setContext( a, b, context ) {
+	_setBWasUndone( b, context );
```
Comment (Reinmar) [inline src/model/delta/transform.js]: Do we only undo `b`s?

**Comment by Reinmar** [comment]
I'm merging this PR, but please answer https://github.com/ckeditor/ckeditor5-engine/pull/1052#discussion_r130111839 for the future reference.

File: src/model/delta/transform.js (hunk 2 above)
Comment (scofalik) [inline src/model/delta/transform.js]: Your question is almost correct ;).

We need only information about delta `b`, because delta `a` cannot be undone delta, because we are transforming it at the moment, so it is not yet applied. For delta `a` it would always be `false`.
