### PR TITLE
Fixed: AttributeElement with bogus BR should be pushed after all ui elements

### LINKED ISSUE #1072: Force rendering bogus BR after UI elements
At the moment, an attribute element that is in otherwise empty container element receives bogus BR:
```html
<p>
  <strong><br /></strong>
</p>
```
However it causes a problem when there is also a UI element in that container:
```html
<p>
  <strong><br /></strong>
  <span class="myUi"></span>
</p>
```
Because the UI element is rendered incorrectly.

We should force rendering such attribute element after all UI elements. The attribute element should be pushed if its parent has no non-UI elements.

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: `AttributeElement` with bogus `<br />` will now be placed after all UI elements which will fix how those elements are rendered. Closes #1072.

### CODE REVIEW

File: src/conversion/model-selection-to-view-converters.js [hunk 1]
```diff
@@ -200,12 +200,34 @@ function wrapCollapsedSelectionPosition( modelSelection, viewSelection, viewElem
 	}
 
 	let viewPosition = viewSelection.getFirstPosition();
+
+	// This hack is supposed to place attribute element *after* all ui elements if the attribute element would be
+	// the only non-ui child and thus receive a block filler.
```
Comment (pjasiun) [inline src/conversion/model-selection-to-view-converters.js]: This comment tells what you do, but not why you do it. At least link to the issue is needed.

**Comment by scofalik** [comment]
I've added more explanation to the comment.
