### PR TITLE
T/1436: Fixing selection that cross limit node boundaries.

### LINKED ISSUE #1436: Automatic selection post-fixer – part 2
When reviewing https://github.com/ckeditor/ckeditor5-engine/pull/1431 I spotted a couple of issues which we weren't able to fix back then. Mainly – element selection of non-objects and correct way of fixing selections crossing limit boundaries.

### PR DESCRIPTION
**Pull request by jodator**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other: Fixing selection that cross limit node boundaries. Closes #1436.

Other: The `schema.getLimitElement()` method now accepts also `Range` and `Position` as a parameter.

---

### Additional information

This PR comes with some fixes in other repos all branches are available at https://github.com/ckeditor/ckeditor5/tree/%23t/ckeditor5-engine/1436:

* https://github.com/ckeditor/ckeditor5-enter/pull/55
* https://github.com/ckeditor/ckeditor5-list/pull/106
* https://github.com/ckeditor/ckeditor5-table/pull/81
* https://github.com/ckeditor/ckeditor5-undo/pull/87
* https://github.com/ckeditor/ckeditor5-widget/pull/45

### CODE REVIEW

**Comment by Reinmar** [comment]
Two conditions are not covered when running just the post-fixer's tests: 

image

File: src/model/utils/selection-post-fixer.js [hunk 1]
```diff
@@ -146,27 +146,87 @@ function tryFixingCollapsedRange( range, schema ) {
...
 // @param {module:engine/model/schema~Schema} schema
 // @returns {module:engine/model/range~Range|null} Returns fixed range or null if range is valid.
-function tryFixingNonCollpasedRage( range, schema ) {
-	// No need to check flat ranges as they will not cross node boundary.
-	if ( range.isFlat ) {
+function tryFixingNonCollapsedRage( range, schema ) {
+	const start = range.start;
+	const end = range.end;
+
+	// Flat range on the same text node is always valid - no need to fix:
```
Comment (Reinmar) [inline src/model/utils/selection-post-fixer.js]: I think that this comment isn't entirely correct – I mean the "same" part. What about:

```html
<p>f[oo<inlineWidget/>ba]r</p>
```

Also, what about:

```html
<p>[foo]</p>
```

In this case, neither the start's nor end's `textNode` getter will return something.

And there's one more case which is missed here:

```html
<p>[<inlineWidget/>foo<inlineWidget/>]</p>
```

You might've had a different goal by adding this condition – filtering some cases which might be broken by the following logic of this function. But, if the logic of such a check isn't "complete" in a bigger picture, a wider context of the entire algorithm, then it may be misleading. So, instead of patching this algorithm for a hidden purpose, let's thing wider.

E.g. what kind of non-collapsed selections don't need to be fixed? Those which meet the following criteria (all):

* `schema.getLimitElement( range.start ) == schema.getLimitElement( range.end )` – it means the selection starts and ends in the same limit element, so it does not cross any limit element boundary. If a range violates this rule, it needs to be extended to cover the lowest common limit element of both its ends (`schem.getLimitElement( range )`).

   Note: Right now, `schema.getLimitElement()` works only with entire selections, but it's not hard to "downgrade" it to support single ranges (returns LCA like for the entire selection) and single positions (returns a lowest limit element in which this position is contained) too.
* `schema.checkChild( range.start, '$text' ) && schema.checkChild( range.end, '$text' )` – both its ends are in a place where text is allowed. They don't need to be placed in/next to a text (`<p>[<inlineWidget/>...`) but it's enough that text is allowed there.

   Note: A range containing a block widget will not be rooted in a place where text is allowed, so it will pass this check. However, it doesn't mean it's incorrect – I was describing a range which is certainly correct (i.e. a possible early return check), not an algorithm for deciding whether a range is correct or not.

Comment (Reinmar) [reply src/model/utils/selection-post-fixer.js]: By structuring the algorithm as I described above, the rules by which it works will be easier to read. Right now, it consists of "let's try fixing this, let's try that" which is harder for me to digest.

File: tests/model/schema.js [hunk 2]
```diff
@@ -1123,12 +1123,12 @@ describe( 'Schema', () => {
 			schema.extend( 'img', { allowAttributes: 'bold' } );
 			schema.extend( '$text', { allowIn: 'img' } );
 
-			setData( model, '[<p>foo<img>xxx</img>bar</p>]' );
```
Comment (Reinmar) [inline tests/model/schema.js]: This changes the semantics of this test. Let's better use `parse()`, especially that later on we do `selection.getRanges()` anyway.

File: tests/model/utils/selection-post-fixer.js [hunk 3]
```diff
@@ -59,37 +63,41 @@ describe( 'Selection post-fixer', () => {
 		} );
 
 		it( 'should react to structure changes', () => {
+			setModelData( model, '<paragraph>[]foo</paragraph><image></image>' );
```
Comment (Reinmar) [inline tests/model/utils/selection-post-fixer.js]: What was wrong with this test?

Comment (Reinmar) [reply tests/model/utils/selection-post-fixer.js]: Ah, ok, you're simplifying the test.

**Comment by Reinmar** [comment]
OK, so far, the most important bit is my comment about structuring this algorithm. I think you could try to restructure it so the rules by which it works are more visible. I *think* I described the outline in my comment, but of course that's just the outline. You also need the "fix it" parts. In general, it should look more or less like this:

1. check something
  * if it's wrong fix it; if possible return here; if not, continue;
2. check something else
  * if it's wrong fix it; if possible return here; if not, continue;
3. ... and so on

**Comment by jodator** [comment]
@Reinmar ready to re-review.

File: src/model/schema.js [hunk 4]
```diff
@@ -586,22 +586,32 @@ export default class Schema {
 	 * Returns the lowest {@link module:engine/model/schema~Schema#isLimit limit element} containing the entire
 	 * selection or the root otherwise.
 	 *
-	 * @param {module:engine/model/selection~Selection|module:engine/model/documentselection~DocumentSelection} selection
+	 * @param {module:engine/model/selection~Selection|module:engine/model/documentselection~DocumentSelection} selectionOrRangeOrPosition
```
Comment (Reinmar) [inline src/model/schema.js]: You forgot to update the type.

File: tests/conversion/downcast-selection-converters.js [hunk 5]
```diff
@@ -542,7 +542,7 @@ describe( 'downcast-selection-converters', () => {
 		it( 'should add a class to the selected table cell', () => {
 			test(
 				// table tr#0 |td#0, table tr#0 td#0|
```
Comment (Reinmar) [inline tests/conversion/downcast-selection-converters.js]: Are the comments up to date now?

File: tests/conversion/downcast-selection-converters.js [hunk 6]
```diff
@@ -551,9 +551,9 @@ describe( 'downcast-selection-converters', () => {
 		it( 'should not be used if selection contains more than just a table cell', () => {
 			test(
 				// table tr td#1, table tr#2
```
Comment (Reinmar) [inline tests/conversion/downcast-selection-converters.js]: And here too?

File: tests/model/schema.js [hunk 7]
```diff
@@ -983,6 +983,28 @@ describe( 'Schema', () => {
 
 			expect( schema.getLimitElement( doc.selection ) ).to.equal( root );
 		} );
+
+		it( 'accepts range as an argument', () => {
+			schema.extend( 'article', { isLimit: true } );
+			schema.extend( 'section', { isLimit: true } );
+
+			setData( model, '<div><section><article><paragraph>foo[]bar</paragraph></article></section></div>' );
```
Comment (Reinmar) [inline tests/model/schema.js]: Why do you set a selection anywhere if you're testing if this method works with a range?

You can use `parse()` here, btw.

File: tests/model/schema.js [hunk 8]
```diff
@@ -1101,7 +1123,13 @@ describe( 'Schema', () => {
 				}
 			} );
 
-			setData( model, '<p>foo<img />bar</p>' );
+			// Parse data string to model.
+			const parsedResult = setData._parse( '[<p>foo<img />bar</p>]', model.schema, { context: [ root.name ] } );
```
Comment (Reinmar) [inline tests/model/schema.js]: Use the public export.

File: tests/model/schema.js (hunk 2 above)
Comment (Reinmar) [reply tests/model/schema.js]: This is still not resolved.

File: tests/model/utils/deletecontent.js [hunk 9]
```diff
@@ -621,7 +621,7 @@ describe( 'DataController utils', () => {
 				deleteContent( model, selection );
 
 				expect( getData( model, { rootName: 'bodyRoot' } ) )
-					.to.equal( '[<paragraph>x</paragraph>]<paragraph></paragraph><paragraph>z</paragraph>' );
+					.to.equal( '<paragraph>[x]</paragraph><paragraph></paragraph><paragraph>z</paragraph>' );
```
Comment (Reinmar) [inline tests/model/utils/deletecontent.js]: You can change the initial selection too, so this test is less confusing (we're not checking the sel post-fixer here).

File: tests/model/utils/deletecontent.js [hunk 10]
```diff
@@ -644,7 +644,16 @@ describe( 'DataController utils', () => {
...
 				);
 
-				deleteContent( model, doc.selection );
+				model.change( writer => {
+					// Set selection to[<heading1>yyy</heading1>] in change() block due to selection post-fixer.
+					const range = new Range(
+						new Position( doc.getRoot( 'bodyRoot' ), [ 1 ] ),
+						new Position( doc.getRoot( 'bodyRoot' ), [ 2 ] )
+					);
+					writer.setSelection( range );
```
Comment (Reinmar) [inline tests/model/utils/deletecontent.js]: You don't have to set that selection. `deleteContent()` can work with any selection.

File: tests/model/utils/deletecontent.js [hunk 11]
```diff
@@ -657,7 +666,16 @@ describe( 'DataController utils', () => {
...
 				);
 
-				deleteContent( model, doc.selection );
+				model.change( writer => {
+					// Set selection to[<heading1>yyy</heading1><paragraph>yyy</paragraph>] in change() block due to selection post-fixer.
+					const range = new Range(
+						new Position( doc.getRoot( 'bodyRoot' ), [ 1 ] ),
+						new Position( doc.getRoot( 'bodyRoot' ), [ 3 ] )
+					);
+					writer.setSelection( range );
```
Comment (Reinmar) [inline tests/model/utils/deletecontent.js]: The same as above– no need to set it. Also, it'd be good if you changed it in the `setData()` call above to something irrelevant to this test to not create a confusion.

File: tests/model/utils/deletecontent.js (hunk 10 above)
Comment (Reinmar) [reply tests/model/utils/deletecontent.js]: Also, it'd be good if you changed it in the `setData()` call above to something irrelevant to this test to not create a confusion.

File: tests/model/schema.js [hunk 12]
```diff
@@ -1101,7 +1123,13 @@ describe( 'Schema', () => {
...
+
+			// Set parsed model data to prevent selection post-fixer from running.
+			model.change( writer => {
+				writer.insert( parsedResult.model, root );
```
[the remark this answers is not in the document]
Comment (jodator) [reply tests/model/schema.js]: I don't really know how to do that  - AFAICS it's easiest to just use `writer.insert( node, root)`...

[the remark this answers is not in the document]
Comment (Reinmar) [reply tests/model/schema.js]: The method we're testing  there `schema.getValidRanges()` doesn't need to work on on a piece of a tree which is in the model. At least – I think that doesn't need that. It should be able to work on a detached tree. 

OTOH, we can leave  it with the `insert()` and test it just like it will be used most of the time (in an attached tree).

**Comment by jodator** [comment]
@Reinmar the fix is on the branch already.

**Comment by Reinmar** [comment]
🎉

**Comment by jodator** [comment]
@Mgsy As this looks like finished could you check how the selection on widgets behaves now?

Also this one fixes selection on images in firefox: https://github.com/ckeditor/ckeditor5-engine/issues/1440 (not the flashing part though - only the selection problems).

Also on FF the multi-range selection that is fixed (ie on widgets) should be merge into one big (https://github.com/ckeditor/ckeditor5-engine/issues/1440#issuecomment-402653775).

**Comment by Mgsy** [comment]
Basically, it works fine (except Edge, where a widget steals the selection ) 👌 

There is a problem with nested editables, see caption in **Chrome**:

bug_cke5

or table in **Firefox**

bug_cke5

**Comment by jodator** [comment]
> There is a problem with nested editables, see the caption in Chrome:

@Mgsy you mean that it blinks? If so I don't think we could do anything in particular in this PR as this is a bit different issue (cc @Reinmar) - we need to stop selection updates somehow do prevent this. I think that a follow-up is needed here.

> or the table in Firefox:

It looks OK (selecting whole table) - could you describe what you mean here since I've might be missing something from the GIF.

**Comment by Reinmar** [comment]
Agree with @jodator regarding the first part – we need to extract this to a separate ticket.

**Comment by Mgsy** [comment]
>It looks OK (selecting whole table) - could you describe what you mean here since I've might be missing something from the GIF.

Yep, that is what I meant - selecting the whole table. As this behaviour is expected, the whole fix looks good to me 👌
