### PR TITLE
Nodes are removed from their old parent when they are appended to new parent

### LINKED ISSUE #1139: Children nodes are inserted to new parent without first removing them from their old parent
I spotted a bug that crashed editor during rendering. It appeared that `Renderer` wants to re-render a part of a tree that is detached from main tree. What was weird about that tree was that detached-root had a child but that child's `parent` property was set to `null`. Similarly, that child also had a child which also had `parent` set to `null`.

After debugging it appeared that in `view.Writer` some nodes were supposed to be moved from one node to another, however those nodes were not removed from their original parent before appending to new parent, which caused this bug.

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: `view` and `model` nodes will now be removed from their old parent when they are added to a new parent to prevent having same node on multiple elements' children lists. Closes #1139.

BREAKING CHANGE: If you will append `view` or `model` node that already has a parent, that node will be first removed from it's parent. This is important if you iterate through element's children and they are moved during that iteration. In that case it's safest to cache the element's children in an array.

### CODE REVIEW

**Comment by scofalik** [comment]
Needed to fix a test in typing https://github.com/ckeditor/ckeditor5-typing/pull/121

File: src/dev-utils/view.js [hunk 1]
```diff
@@ -852,7 +852,7 @@ function _convertViewElements( rootNode ) {
 		const convertedElement = rootNode.is( 'documentFragment' ) ? new ViewDocumentFragment() : _convertElement( rootNode );
 
 		// Convert all child nodes.
-		for ( const child of rootNode.getChildren() ) {
+		for ( const child of [ ...rootNode.getChildren() ] ) {
```
Comment (Reinmar) [inline src/dev-utils/view.js]: COMMMWENTR~!!#@

File: src/model/documentfragment.js [hunk 2]
```diff
@@ -235,6 +235,11 @@ export default class DocumentFragment {
 		nodes = normalize( nodes );
 
 		for ( const node of nodes ) {
+			// If node that is being added to this element is already inside another element, first remove it from the old parent.
+			if ( node.parent !== null ) {
```
Comment (Reinmar) [inline src/model/documentfragment.js]: I'm hesitating whether I'd rather like `if ( node.parent )` or `!== null` ;| Dunno

File: src/dev-utils/view.js (hunk 1 above)
Comment (scofalik) [reply src/dev-utils/view.js]: Why so serious?

Comment (scofalik) [reply src/dev-utils/view.js]: Fixed

File: src/model/documentfragment.js (hunk 2 above)
Comment (scofalik) [reply src/model/documentfragment.js]: `!== null` is easier to find when searching codebase

**Comment by scofalik** [comment]
What's up with this PR?

**Comment by Reinmar** [comment]
W8ing for me having time to check it.
