### PR TITLE
Fixed: LiveRange throwing after executing RenameOperation.

### LINKED ISSUE #624: LivePosition throws error when `RenameOperation` is used
When `RenameOperation` is a cause of `change` event on document, it makes `LivePosition` throw an error. This is because `RenameOperation` does not return `range` property needed by `LivePosition`. This issue was already addressed in `LiveRange` but it was ommited in `LivePosition`. Same fix will apply.

### PR DESCRIPTION
**Pull request by scofalik**
Fixes #624

### CODE REVIEW

File: src/model/liveposition.js [hunk 1]
```diff
@@ -123,12 +123,16 @@ export default class LivePosition extends Position {
  */
 function bindWithDocument() {
 	/*jshint validthis: true */
+	// Operation types handled by LivePosition (these are operations that change model tree structure).
+	const supportedTypes = new Set( [ 'insert', 'move', 'remove', 'reinsert' ] );
```
Comment (maxbarnas) [inline src/model/liveposition.js]: Is there a reason to move it up and make it a property of LivePosition class?

Comment (scofalik) [inline src/model/liveposition.js]: It might look better (if it is static), but I don't want to create new `Set` or `Array` each time it is called so it would have to be something like:

```javascript
static get supportedTypes() {
    return supportedTypes;
};
// ... after class declaration
const supportedTypes = new Set( ... );
```

I think we are fine with how it looks like now.
