### PR TITLE
Fix for focus toggling in editable

### LINKED ISSUE #512: Editable loses and regains focus when typing
1. Open http://tests.ckeditor.dev:1030/build/amd/tests/editor-classic/manual/classic
2. Init the editor.
3. Start typing.

See that on each letter isFocused is set to false and then back to true.

### PR DESCRIPTION
**Pull request by szymonkups**
Fixes #512.

### CODE REVIEW

File: src/view/document.js [hunk 1]
```diff
@@ -250,11 +247,7 @@ export default class Document {
 	 * before rendering and re-enabled after that.
```
Comment (pjasiun) [inline src/view/document.js]: It would be worth to mention that this method fire `render` event.
