### PR TITLE
MarkerDelta transformation should consider ranges equal to null.

### LINKED ISSUE #943: Editor crashes when transforming MarkerDelta that has null as one of its ranges.
Editor crashes when transforming `MarkerDelta` that has a `MarkerOperation` with `null` as one of its ranges.

`MarkerOperation` may have `null` values, for example when it creates or removes a marker. This was not taken into consideration when writing transformation in `engine/model/delta/basic-transformations~transformMarkerDelta`.

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: `MarkerDelta` transformation should no longer cause editor to crash, if a `MarkerOperation` had `null` as it's `oldRange` or `newRange`. Closes #943.

### CODE REVIEW

File: tests/model/delta/transform/markerdelta.js [hunk 1]
```diff
@@ -232,4 +232,17 @@ describe( 'transform', () => {
...
+	it( 'transforming MarkerDelta with null ranges should not crash', () => {
+		const markerDelta = getMarkerDelta( 'name', null, null, baseVersion );
+
+		// Transform `markerDelta` by any other delta that has a special transformation case with `MarkerDelta`.
+		const wrapElement = new Element( 'w' );
+		const wrapRange = new Range( new Position( root, [ 1 ] ), new Position( root, [ 2 ] ) );
+		const wrapDelta = getWrapDelta( wrapRange, wrapElement, baseVersion );
+
+		expect( () => {
+			transform( markerDelta, wrapDelta );
```
Comment (Reinmar) [inline tests/model/delta/transform/markerdelta.js]: But what's the expected behaviour of such transformation?

**Comment by Reinmar** [comment]
I left one comment. Wouldn't we like to test what's the expected output?

**Comment by scofalik** [comment]
You are absolutely right.

**Comment by scofalik** [comment]
Fixed
