### PR TITLE
Model#deleteContent will not throw anymore if the passed selection is in the graveyard root

### LINKED ISSUE #1706: `deleteContent` in graveyard fails
If `deleteContent()` is executed on a selection which is in the graveyard root it will fail. It's because `startPos` is created as a static position but since it is in the graveyard, it should be updated:

```js
const startPos = selRange.start;
// ...
writer.remove( selRange );
// ...
mergeBranches( writer, startPos, endPos ); // <-- Incorrect `startPos` is used.
```

There are two possible solutions for this:

1. Make `startPos` a `LivePosition`.
2. Cancel `deleteContent` if `selRange` is in the graveyard.

We chose the second option because it is less prone to an error and generates no operations.

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: `Model#deleteContent` will not throw anymore if the passed selection is in the graveyard root. Closes #1706.

### CODE REVIEW

File: src/model/utils/deletecontent.js [hunk 1]
```diff
@@ -63,6 +63,13 @@ export default function deleteContent( model, selection, options = {} ) {
 	const schema = model.schema;
 
 	model.change( writer => {
+		const selRange = selection.getFirstRange();
+
+		// If the selection is already removed, don't do anything.
+		if ( selRange.root.rootName == '$graveyard' ) {
```
Comment (Reinmar) [inline src/model/utils/deletecontent.js]: Why not outside, right after checking `selection.isCollapsed`? It seems more natural to have there all the early returns. Since you've put it here, in the `model.change()` block I had to scroll the code down to see if there's anything after `model.change()` that might need (or perhaps should not) be executed.

Comment (scofalik) [reply src/model/utils/deletecontent.js]: I did it like this to be sure that the selection doesn't get into the graveyard before `model.change` actually executes, but I forgot that it executes right away in all circumstances (as opposed to `enqueueChange`). Will fix.
